CREATE TABLE [dbo].[IPGOD.IPGOD207_TM_EXAM_INFO] (
    [TM_NUMBER]   VARCHAR (50) NOT NULL,
    [REPORT_NO]   VARCHAR (50) NULL,
    [CLASS_COUNT] VARCHAR (50) NULL, 
    CONSTRAINT [PK_IPGOD.IPGOD207_TM_EXAM_INFO] PRIMARY KEY ([TM_NUMBER])
);

