CREATE TABLE [dbo].[IPGOD.IPGOD203_TM_INFO] (
    [TM_NUMBER]                    INT           NOT NULL,
    [STATUS_CODE]                  BIGINT        NULL,
    [STATUS_CODE_DESC]             VARCHAR (102) NULL,
    [TYPE_OF_MARK_CODE]            VARCHAR (39)  NULL,
    [EXPEDITE_FLAG_IND]            VARCHAR (9)   NULL,
    [NON_USE_FLAG_IND]             VARCHAR (9)   NULL,
    [CPI_STATUS_CODE]              VARCHAR (129) NULL,
    [LIVE_OR_DEAD_CODE]            VARCHAR (12)  NULL,
    [TRADEMARK_TYPE]               VARCHAR (48)  NULL,
    [LODGEMENT_DATE]               DATETIME      NULL,
    [PRIORITY_DATE]                DATETIME      NULL,
    [DIVISIONAL_DATE]              DATETIME      NULL,
    [KIND_COLOUR_IND]              VARCHAR (9)   NULL,
    [KIND_SCENT_IND]               VARCHAR (6)   NULL,
    [KIND_SHAPE_IND]               VARCHAR (9)   NULL,
    [KIND_SOUND_IND]               VARCHAR (9)   NULL,
    [ACCEPTANCE_DUE_DATE]          DATETIME      NULL,
    [SEALING_DUE_DATE]             DATETIME      NULL,
    [REGISTERED_FROM_DATE]         DATETIME      NULL,
    [SEALING_DATE]                 DATETIME      NULL,
    [RENEWAL_DUE_DATE]             DATETIME      NULL,
    [DIVISIONAL_NUMBER]            BIGINT        NULL,
    [PART_ASSIGN_PARENT_NUMBER]    BIGINT        NULL,
    [PRIORITY_NUMBER]              VARCHAR (45)  NULL,
    [PRIORITY_COUNTRY_CODE]        VARCHAR (6)   NULL,
    [SECTION45_APPLICATION_CODE]   VARCHAR (6)   NULL,
    [COURT_ORDERS_IND]             VARCHAR (9)   NULL,
    [IR_NUMBER_NOTIFY_DATE]        DATETIME      NULL,
    [IR_NUMBER]                    BIGINT        NULL,
    [IR_NUMBER_EXTENSION_VALUE]    VARCHAR (MAX) NULL,
    [PART_TRANSFORM_PARENT_NUMBER] VARCHAR (MAX) NULL,
    [TRANSFORM_IR_NUMBER]          BIGINT        NULL,
    [TRANSFORM_IR_EXTENSION_NO]    VARCHAR (MAX) NULL,
    [IR_RENEWAL_DUE_DATE]          DATETIME      NULL,
    [ACT1955_REG_ACPT_CODE]        VARCHAR (30)  NULL,
    [REVOCATION_ACPT_PEND_IND]     VARCHAR (9)   NULL,
    [GS_ASSISTANCE_IND]            VARCHAR (6)   NULL,
    [LODGEMENT_TYPE_CODE]          VARCHAR (39)  NULL, 
    CONSTRAINT [PK_IPGOD.IPGOD203_TM_INFO] PRIMARY KEY ([TM_NUMBER])
);

